# Generated by Django 4.2.25 on 2025-10-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description_short",
                    models.TextField(blank=True, verbose_name="Краткое описание"),
                ),
                (
                    "description_long",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                ("lng", models.FloatField(verbose_name="Долгота")),
                ("lat", models.FloatField(verbose_name="Широта")),
            ],
        ),
    ]
