# Generated by Django 4.2.25 on 2025-10-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_placeimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="placeimage",
            name="position",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Позиция"
            ),
        ),
    ]
