# Generated by Django 4.2.25 on 2025-10-23 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_placeimage_options_placeimage_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Полное описание"
            ),
        ),
    ]
